name: glinseal-static
static_sites:
  - name: web
    github:
      deploy_on_push: true
      branch: main
      repo: fitin007/GlinsealStaticWeb
    dockerfile_path: Dockerfile.static
    output_dir: /app/public
